Set version of netty-transport to 4.1.15.Final as well.
I had a java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater because of conflicting netty versions.
This pr updates the old(maybe forgotten) netty dependencies to 4.1.15.Final.